import './styles/globals.css';
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Strynexus App',
  description: 'Generated by Bc. Michael Hajný',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
      {console.log(children)}
    </html>
  )
}
